// Optimized Material-UI imports
export { Button } from '@mui/material/Button';
export { TextField } from '@mui/material/TextField';
export { Select } from '@mui/material/Select';
export { MenuItem } from '@mui/material/MenuItem';
export { Dialog } from '@mui/material/Dialog';
export { DialogTitle } from '@mui/material/DialogTitle';
export { DialogContent } from '@mui/material/DialogContent';
export { DialogActions } from '@mui/material/DialogActions';
export { Alert } from '@mui/material/Alert';
export { AlertTitle } from '@mui/material/AlertTitle';
export { Typography } from '@mui/material/Typography';
export { CircularProgress } from '@mui/material/CircularProgress';
export { LinearProgress } from '@mui/material/LinearProgress';
export { Box } from '@mui/material/Box';
export { Paper } from '@mui/material/Paper';
export { Card } from '@mui/material/Card';
export { CardContent } from '@mui/material/CardContent';
export { CardActions } from '@mui/material/CardActions';
export { FormControl } from '@mui/material/FormControl';
export { InputLabel } from '@mui/material/InputLabel';
export { createTheme, ThemeProvider } from '@mui/material/styles';
export { CssBaseline } from '@mui/material/CssBaseline';